# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_master_slave_test.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_master_slave_test(object):
    def setupUi(self, Dialog_master_slave_test):
        Dialog_master_slave_test.setObjectName("Dialog_master_slave_test")
        Dialog_master_slave_test.resize(1241, 600)
        self.label_master_slave = QtWidgets.QLabel(Dialog_master_slave_test)
        self.label_master_slave.setGeometry(QtCore.QRect(100, 20, 781, 41))
        self.label_master_slave.setObjectName("label_master_slave")
        self.label_pic_master_slave = QtWidgets.QLabel(Dialog_master_slave_test)
        self.label_pic_master_slave.setGeometry(QtCore.QRect(20, 10, 61, 61))
        self.label_pic_master_slave.setText("")
        self.label_pic_master_slave.setObjectName("label_pic_master_slave")
        self.group_fan_strength = QtWidgets.QGroupBox(Dialog_master_slave_test)
        self.group_fan_strength.setGeometry(QtCore.QRect(20, 80, 411, 251))
        self.group_fan_strength.setObjectName("group_fan_strength")
        self.group_fan_strength_auto = QtWidgets.QGroupBox(self.group_fan_strength)
        self.group_fan_strength_auto.setGeometry(QtCore.QRect(20, 30, 101, 201))
        self.group_fan_strength_auto.setObjectName("group_fan_strength_auto")
        self.table_fan_strength_auto = QtWidgets.QTableWidget(self.group_fan_strength_auto)
        self.table_fan_strength_auto.setGeometry(QtCore.QRect(20, 30, 61, 141))
        self.table_fan_strength_auto.setObjectName("table_fan_strength_auto")
        self.table_fan_strength_auto.setColumnCount(2)
        self.table_fan_strength_auto.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_auto.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_auto.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_auto.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_auto.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_auto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_auto.setItem(4, 1, item)
        self.check_fan_strength_auto = QtWidgets.QCheckBox(self.group_fan_strength_auto)
        self.check_fan_strength_auto.setGeometry(QtCore.QRect(30, 180, 16, 16))
        self.check_fan_strength_auto.setText("")
        self.check_fan_strength_auto.setObjectName("check_fan_strength_auto")
        self.group_fan_strength_high = QtWidgets.QGroupBox(self.group_fan_strength)
        self.group_fan_strength_high.setGeometry(QtCore.QRect(160, 30, 101, 201))
        self.group_fan_strength_high.setObjectName("group_fan_strength_high")
        self.table_fan_strength_high = QtWidgets.QTableWidget(self.group_fan_strength_high)
        self.table_fan_strength_high.setGeometry(QtCore.QRect(20, 30, 61, 141))
        self.table_fan_strength_high.setObjectName("table_fan_strength_high")
        self.table_fan_strength_high.setColumnCount(2)
        self.table_fan_strength_high.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_high.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_high.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_high.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_high.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_high.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_high.setItem(4, 1, item)
        self.check_fan_strength_high = QtWidgets.QCheckBox(self.group_fan_strength_high)
        self.check_fan_strength_high.setGeometry(QtCore.QRect(30, 180, 16, 16))
        self.check_fan_strength_high.setText("")
        self.check_fan_strength_high.setObjectName("check_fan_strength_high")
        self.group_fan_strength_quiet = QtWidgets.QGroupBox(self.group_fan_strength)
        self.group_fan_strength_quiet.setGeometry(QtCore.QRect(290, 30, 101, 201))
        self.group_fan_strength_quiet.setObjectName("group_fan_strength_quiet")
        self.table_fan_strength_quiet = QtWidgets.QTableWidget(self.group_fan_strength_quiet)
        self.table_fan_strength_quiet.setGeometry(QtCore.QRect(20, 30, 61, 141))
        self.table_fan_strength_quiet.setObjectName("table_fan_strength_quiet")
        self.table_fan_strength_quiet.setColumnCount(2)
        self.table_fan_strength_quiet.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_quiet.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_quiet.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_quiet.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_quiet.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_strength_quiet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_strength_quiet.setItem(4, 1, item)
        self.check_fan_strength_quiet = QtWidgets.QCheckBox(self.group_fan_strength_quiet)
        self.check_fan_strength_quiet.setGeometry(QtCore.QRect(30, 180, 16, 16))
        self.check_fan_strength_quiet.setText("")
        self.check_fan_strength_quiet.setObjectName("check_fan_strength_quiet")
        self.group_fan_new_strength = QtWidgets.QGroupBox(Dialog_master_slave_test)
        self.group_fan_new_strength.setGeometry(QtCore.QRect(460, 80, 411, 251))
        self.group_fan_new_strength.setObjectName("group_fan_new_strength")
        self.group_fan_new_strength_hihi = QtWidgets.QGroupBox(self.group_fan_new_strength)
        self.group_fan_new_strength_hihi.setGeometry(QtCore.QRect(20, 30, 101, 201))
        self.group_fan_new_strength_hihi.setObjectName("group_fan_new_strength_hihi")
        self.table_fan_new_strength_hihi = QtWidgets.QTableWidget(self.group_fan_new_strength_hihi)
        self.table_fan_new_strength_hihi.setGeometry(QtCore.QRect(20, 30, 61, 141))
        self.table_fan_new_strength_hihi.setObjectName("table_fan_new_strength_hihi")
        self.table_fan_new_strength_hihi.setColumnCount(2)
        self.table_fan_new_strength_hihi.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_hihi.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_hihi.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_hihi.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_hihi.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_hihi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_hihi.setItem(4, 1, item)
        self.check_fan_new_strength_hihi = QtWidgets.QCheckBox(self.group_fan_new_strength_hihi)
        self.check_fan_new_strength_hihi.setGeometry(QtCore.QRect(30, 180, 16, 16))
        self.check_fan_new_strength_hihi.setText("")
        self.check_fan_new_strength_hihi.setObjectName("check_fan_new_strength_hihi")
        self.group_fan_new_strength_mehi = QtWidgets.QGroupBox(self.group_fan_new_strength)
        self.group_fan_new_strength_mehi.setGeometry(QtCore.QRect(160, 30, 101, 201))
        self.group_fan_new_strength_mehi.setObjectName("group_fan_new_strength_mehi")
        self.table_fan_new_strength_mehi = QtWidgets.QTableWidget(self.group_fan_new_strength_mehi)
        self.table_fan_new_strength_mehi.setGeometry(QtCore.QRect(20, 30, 61, 141))
        self.table_fan_new_strength_mehi.setObjectName("table_fan_new_strength_mehi")
        self.table_fan_new_strength_mehi.setColumnCount(2)
        self.table_fan_new_strength_mehi.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_mehi.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_mehi.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_mehi.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_mehi.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_mehi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_mehi.setItem(4, 1, item)
        self.check_fan_new_strength_mehi = QtWidgets.QCheckBox(self.group_fan_new_strength_mehi)
        self.check_fan_new_strength_mehi.setGeometry(QtCore.QRect(30, 180, 16, 16))
        self.check_fan_new_strength_mehi.setText("")
        self.check_fan_new_strength_mehi.setObjectName("check_fan_new_strength_mehi")
        self.group_fan_new_strength_lolo = QtWidgets.QGroupBox(self.group_fan_new_strength)
        self.group_fan_new_strength_lolo.setGeometry(QtCore.QRect(290, 30, 101, 201))
        self.group_fan_new_strength_lolo.setObjectName("group_fan_new_strength_lolo")
        self.table_fan_new_strength_lolo = QtWidgets.QTableWidget(self.group_fan_new_strength_lolo)
        self.table_fan_new_strength_lolo.setGeometry(QtCore.QRect(20, 30, 61, 141))
        self.table_fan_new_strength_lolo.setObjectName("table_fan_new_strength_lolo")
        self.table_fan_new_strength_lolo.setColumnCount(2)
        self.table_fan_new_strength_lolo.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_lolo.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_lolo.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_lolo.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_lolo.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fan_new_strength_lolo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_fan_new_strength_lolo.setItem(4, 1, item)
        self.check_fan_new_strength_lolo = QtWidgets.QCheckBox(self.group_fan_new_strength_lolo)
        self.check_fan_new_strength_lolo.setGeometry(QtCore.QRect(30, 180, 16, 16))
        self.check_fan_new_strength_lolo.setText("")
        self.check_fan_new_strength_lolo.setObjectName("check_fan_new_strength_lolo")
        self.group_horizontal = QtWidgets.QGroupBox(Dialog_master_slave_test)
        self.group_horizontal.setGeometry(QtCore.QRect(30, 350, 581, 221))
        self.group_horizontal.setObjectName("group_horizontal")
        self.group_horizontal_1 = QtWidgets.QGroupBox(self.group_horizontal)
        self.group_horizontal_1.setGeometry(QtCore.QRect(40, 40, 120, 80))
        self.group_horizontal_1.setObjectName("group_horizontal_1")
        self.table_horizontal_1 = QtWidgets.QTableWidget(self.group_horizontal_1)
        self.table_horizontal_1.setGeometry(QtCore.QRect(30, 10, 61, 141))
        self.table_horizontal_1.setObjectName("table_horizontal_1")
        self.table_horizontal_1.setColumnCount(2)
        self.table_horizontal_1.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_1.setItem(4, 1, item)
        self.check_horizontal_1 = QtWidgets.QCheckBox(self.group_horizontal_1)
        self.check_horizontal_1.setGeometry(QtCore.QRect(90, 30, 16, 16))
        self.check_horizontal_1.setText("")
        self.check_horizontal_1.setObjectName("check_horizontal_1")
        self.group_horizontal_2 = QtWidgets.QGroupBox(self.group_horizontal)
        self.group_horizontal_2.setGeometry(QtCore.QRect(200, 50, 120, 80))
        self.group_horizontal_2.setObjectName("group_horizontal_2")
        self.table_horizontal_2 = QtWidgets.QTableWidget(self.group_horizontal_2)
        self.table_horizontal_2.setGeometry(QtCore.QRect(30, 30, 61, 141))
        self.table_horizontal_2.setObjectName("table_horizontal_2")
        self.table_horizontal_2.setColumnCount(2)
        self.table_horizontal_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_2.setItem(4, 1, item)
        self.check_horizontal_2 = QtWidgets.QCheckBox(self.group_horizontal_2)
        self.check_horizontal_2.setGeometry(QtCore.QRect(30, 0, 16, 16))
        self.check_horizontal_2.setText("")
        self.check_horizontal_2.setObjectName("check_horizontal_2")
        self.group_horizontal_3 = QtWidgets.QGroupBox(self.group_horizontal)
        self.group_horizontal_3.setGeometry(QtCore.QRect(360, 50, 120, 80))
        self.group_horizontal_3.setObjectName("group_horizontal_3")
        self.table_horizontal_3 = QtWidgets.QTableWidget(self.group_horizontal_3)
        self.table_horizontal_3.setGeometry(QtCore.QRect(40, 30, 61, 141))
        self.table_horizontal_3.setObjectName("table_horizontal_3")
        self.table_horizontal_3.setColumnCount(2)
        self.table_horizontal_3.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_3.setItem(4, 1, item)
        self.check_horizontal_3 = QtWidgets.QCheckBox(self.group_horizontal_3)
        self.check_horizontal_3.setGeometry(QtCore.QRect(10, 20, 16, 16))
        self.check_horizontal_3.setText("")
        self.check_horizontal_3.setObjectName("check_horizontal_3")
        self.group_horizontal_4 = QtWidgets.QGroupBox(self.group_horizontal)
        self.group_horizontal_4.setGeometry(QtCore.QRect(240, 140, 120, 80))
        self.group_horizontal_4.setObjectName("group_horizontal_4")
        self.table_horizontal_4 = QtWidgets.QTableWidget(self.group_horizontal_4)
        self.table_horizontal_4.setGeometry(QtCore.QRect(60, 20, 61, 141))
        self.table_horizontal_4.setObjectName("table_horizontal_4")
        self.table_horizontal_4.setColumnCount(2)
        self.table_horizontal_4.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_horizontal_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_horizontal_4.setItem(4, 1, item)
        self.check_horizontal_4 = QtWidgets.QCheckBox(self.group_horizontal_4)
        self.check_horizontal_4.setGeometry(QtCore.QRect(30, 30, 16, 16))
        self.check_horizontal_4.setText("")
        self.check_horizontal_4.setObjectName("check_horizontal_4")
        self.group_vertical = QtWidgets.QGroupBox(Dialog_master_slave_test)
        self.group_vertical.setGeometry(QtCore.QRect(640, 360, 521, 211))
        self.group_vertical.setObjectName("group_vertical")
        self.group_vertical_1 = QtWidgets.QGroupBox(self.group_vertical)
        self.group_vertical_1.setGeometry(QtCore.QRect(30, 40, 120, 80))
        self.group_vertical_1.setObjectName("group_vertical_1")
        self.table_vertical_1 = QtWidgets.QTableWidget(self.group_vertical_1)
        self.table_vertical_1.setGeometry(QtCore.QRect(40, 30, 61, 141))
        self.table_vertical_1.setObjectName("table_vertical_1")
        self.table_vertical_1.setColumnCount(2)
        self.table_vertical_1.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_1.setItem(4, 1, item)
        self.check_vertical_1 = QtWidgets.QCheckBox(self.group_vertical_1)
        self.check_vertical_1.setGeometry(QtCore.QRect(20, 30, 16, 16))
        self.check_vertical_1.setText("")
        self.check_vertical_1.setObjectName("check_vertical_1")
        self.group_vertical_2 = QtWidgets.QGroupBox(self.group_vertical)
        self.group_vertical_2.setGeometry(QtCore.QRect(190, 30, 120, 80))
        self.group_vertical_2.setObjectName("group_vertical_2")
        self.table_vertical_2 = QtWidgets.QTableWidget(self.group_vertical_2)
        self.table_vertical_2.setGeometry(QtCore.QRect(40, 40, 61, 141))
        self.table_vertical_2.setObjectName("table_vertical_2")
        self.table_vertical_2.setColumnCount(2)
        self.table_vertical_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_2.setItem(4, 1, item)
        self.check_vertical_2 = QtWidgets.QCheckBox(self.group_vertical_2)
        self.check_vertical_2.setGeometry(QtCore.QRect(20, 20, 16, 16))
        self.check_vertical_2.setText("")
        self.check_vertical_2.setObjectName("check_vertical_2")
        self.group_vertical_3 = QtWidgets.QGroupBox(self.group_vertical)
        self.group_vertical_3.setGeometry(QtCore.QRect(380, 30, 120, 80))
        self.group_vertical_3.setObjectName("group_vertical_3")
        self.table_vertical_3 = QtWidgets.QTableWidget(self.group_vertical_3)
        self.table_vertical_3.setGeometry(QtCore.QRect(40, 50, 61, 141))
        self.table_vertical_3.setObjectName("table_vertical_3")
        self.table_vertical_3.setColumnCount(2)
        self.table_vertical_3.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_3.setItem(4, 1, item)
        self.check_vertical_3 = QtWidgets.QCheckBox(self.group_vertical_3)
        self.check_vertical_3.setGeometry(QtCore.QRect(30, 20, 16, 16))
        self.check_vertical_3.setText("")
        self.check_vertical_3.setObjectName("check_vertical_3")
        self.group_vertical_4 = QtWidgets.QGroupBox(self.group_vertical)
        self.group_vertical_4.setGeometry(QtCore.QRect(60, 160, 120, 80))
        self.group_vertical_4.setObjectName("group_vertical_4")
        self.table_vertical_4 = QtWidgets.QTableWidget(self.group_vertical_4)
        self.table_vertical_4.setGeometry(QtCore.QRect(30, 10, 61, 141))
        self.table_vertical_4.setObjectName("table_vertical_4")
        self.table_vertical_4.setColumnCount(2)
        self.table_vertical_4.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vertical_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vertical_4.setItem(4, 1, item)
        self.check_vertical_4 = QtWidgets.QCheckBox(self.group_vertical_4)
        self.check_vertical_4.setGeometry(QtCore.QRect(10, 30, 16, 16))
        self.check_vertical_4.setText("")
        self.check_vertical_4.setObjectName("check_vertical_4")
        self.group_other = QtWidgets.QGroupBox(Dialog_master_slave_test)
        self.group_other.setGeometry(QtCore.QRect(910, 80, 341, 221))
        self.group_other.setObjectName("group_other")
        self.group_eco = QtWidgets.QGroupBox(self.group_other)
        self.group_eco.setGeometry(QtCore.QRect(20, 40, 120, 80))
        self.group_eco.setObjectName("group_eco")
        self.table_eco = QtWidgets.QTableWidget(self.group_eco)
        self.table_eco.setGeometry(QtCore.QRect(60, 0, 61, 141))
        self.table_eco.setObjectName("table_eco")
        self.table_eco.setColumnCount(2)
        self.table_eco.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eco.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eco.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eco.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eco.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eco.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_eco.setItem(4, 1, item)
        self.check_eco = QtWidgets.QCheckBox(self.group_eco)
        self.check_eco.setGeometry(QtCore.QRect(40, 30, 16, 16))
        self.check_eco.setText("")
        self.check_eco.setObjectName("check_eco")
        self.group_anti = QtWidgets.QGroupBox(self.group_other)
        self.group_anti.setGeometry(QtCore.QRect(180, 40, 120, 80))
        self.group_anti.setObjectName("group_anti")
        self.table_anti = QtWidgets.QTableWidget(self.group_anti)
        self.table_anti.setGeometry(QtCore.QRect(20, -10, 61, 141))
        self.table_anti.setObjectName("table_anti")
        self.table_anti.setColumnCount(2)
        self.table_anti.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_anti.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_anti.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_anti.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_anti.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_anti.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_anti.setItem(4, 1, item)
        self.check_anti = QtWidgets.QCheckBox(self.group_anti)
        self.check_anti.setGeometry(QtCore.QRect(0, 30, 16, 16))
        self.check_anti.setText("")
        self.check_anti.setObjectName("check_anti")
        self.group_test = QtWidgets.QGroupBox(self.group_other)
        self.group_test.setGeometry(QtCore.QRect(30, 150, 120, 80))
        self.group_test.setObjectName("group_test")
        self.table_test = QtWidgets.QTableWidget(self.group_test)
        self.table_test.setGeometry(QtCore.QRect(60, -20, 61, 141))
        self.table_test.setObjectName("table_test")
        self.table_test.setColumnCount(2)
        self.table_test.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_test.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_test.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_test.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_test.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_test.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_test.setItem(4, 1, item)
        self.check_test = QtWidgets.QCheckBox(self.group_test)
        self.check_test.setGeometry(QtCore.QRect(40, 30, 16, 16))
        self.check_test.setText("")
        self.check_test.setObjectName("check_test")
        self.group_filter = QtWidgets.QGroupBox(self.group_other)
        self.group_filter.setGeometry(QtCore.QRect(200, 150, 120, 80))
        self.group_filter.setObjectName("group_filter")
        self.table_filter = QtWidgets.QTableWidget(self.group_filter)
        self.table_filter.setGeometry(QtCore.QRect(20, 0, 61, 141))
        self.table_filter.setObjectName("table_filter")
        self.table_filter.setColumnCount(2)
        self.table_filter.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_filter.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_filter.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_filter.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_filter.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_filter.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_filter.setItem(4, 1, item)
        self.check_filter = QtWidgets.QCheckBox(self.group_filter)
        self.check_filter.setGeometry(QtCore.QRect(0, 30, 16, 16))
        self.check_filter.setText("")
        self.check_filter.setObjectName("check_filter")
        self.group_sensor = QtWidgets.QGroupBox(Dialog_master_slave_test)
        self.group_sensor.setGeometry(QtCore.QRect(1080, 360, 321, 201))
        self.group_sensor.setObjectName("group_sensor")
        self.group_auto_save = QtWidgets.QGroupBox(self.group_sensor)
        self.group_auto_save.setGeometry(QtCore.QRect(10, 20, 120, 80))
        self.group_auto_save.setObjectName("group_auto_save")
        self.table_auto_save = QtWidgets.QTableWidget(self.group_auto_save)
        self.table_auto_save.setGeometry(QtCore.QRect(40, 30, 61, 141))
        self.table_auto_save.setObjectName("table_auto_save")
        self.table_auto_save.setColumnCount(2)
        self.table_auto_save.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_save.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_save.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_save.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_save.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_save.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_save.setItem(4, 1, item)
        self.check_auto_save = QtWidgets.QCheckBox(self.group_auto_save)
        self.check_auto_save.setGeometry(QtCore.QRect(10, 30, 16, 16))
        self.check_auto_save.setText("")
        self.check_auto_save.setObjectName("check_auto_save")
        self.group_auto_on_off = QtWidgets.QGroupBox(self.group_sensor)
        self.group_auto_on_off.setGeometry(QtCore.QRect(20, 120, 120, 80))
        self.group_auto_on_off.setObjectName("group_auto_on_off")
        self.table_auto_on_off = QtWidgets.QTableWidget(self.group_auto_on_off)
        self.table_auto_on_off.setGeometry(QtCore.QRect(90, 30, 61, 141))
        self.table_auto_on_off.setObjectName("table_auto_on_off")
        self.table_auto_on_off.setColumnCount(2)
        self.table_auto_on_off.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_on_off.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_on_off.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_on_off.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_on_off.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_on_off.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_on_off.setItem(4, 1, item)
        self.check_auto_on_off = QtWidgets.QCheckBox(self.group_auto_on_off)
        self.check_auto_on_off.setGeometry(QtCore.QRect(30, 20, 16, 16))
        self.check_auto_on_off.setText("")
        self.check_auto_on_off.setObjectName("check_auto_on_off")
        self.group_auto_off = QtWidgets.QGroupBox(self.group_sensor)
        self.group_auto_off.setGeometry(QtCore.QRect(160, 30, 120, 121))
        self.group_auto_off.setObjectName("group_auto_off")
        self.check_auto_off = QtWidgets.QCheckBox(self.group_auto_off)
        self.check_auto_off.setGeometry(QtCore.QRect(10, 30, 16, 16))
        self.check_auto_off.setText("")
        self.check_auto_off.setObjectName("check_auto_off")
        self.table_auto_off = QtWidgets.QTableWidget(self.group_auto_off)
        self.table_auto_off.setGeometry(QtCore.QRect(30, 50, 61, 141))
        self.table_auto_off.setObjectName("table_auto_off")
        self.table_auto_off.setColumnCount(2)
        self.table_auto_off.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_off.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_off.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_off.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_off.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_off.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_auto_off.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_auto_off.setItem(5, 1, item)
        self.line = QtWidgets.QFrame(Dialog_master_slave_test)
        self.line.setGeometry(QtCore.QRect(20, 540, 1211, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog_master_slave_test)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(880, 560, 351, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancel_master_slave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_cancel_master_slave.setObjectName("btn_cancel_master_slave")
        self.horizontalLayout.addWidget(self.btn_cancel_master_slave)
        self.btn_create_master_slave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_create_master_slave.setObjectName("btn_create_master_slave")
        self.horizontalLayout.addWidget(self.btn_create_master_slave)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog_master_slave_test)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 560, 171, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_select_all_master_slave = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_select_all_master_slave.setObjectName("btn_select_all_master_slave")
        self.horizontalLayout_2.addWidget(self.btn_select_all_master_slave)

        self.retranslateUi(Dialog_master_slave_test)
        QtCore.QMetaObject.connectSlotsByName(Dialog_master_slave_test)

    def retranslateUi(self, Dialog_master_slave_test):
        _translate = QtCore.QCoreApplication.translate
        Dialog_master_slave_test.setWindowTitle(_translate("Dialog_master_slave_test", "親子機混在試験"))
        self.label_master_slave.setText(_translate("Dialog_master_slave_test", "評価しようとする項目にチェックを入れて、“作成”ボタンを押下してください。"))
        self.group_fan_strength.setTitle(_translate("Dialog_master_slave_test", "風量"))
        self.group_fan_strength_auto.setTitle(_translate("Dialog_master_slave_test", "Auto"))
        item = self.table_fan_strength_auto.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_fan_strength_auto.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_fan_strength_auto.isSortingEnabled()
        self.table_fan_strength_auto.setSortingEnabled(False)
        item = self.table_fan_strength_auto.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_fan_strength_auto.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_fan_strength_auto.setSortingEnabled(__sortingEnabled)
        self.group_fan_strength_high.setTitle(_translate("Dialog_master_slave_test", "High"))
        item = self.table_fan_strength_high.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_fan_strength_high.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_fan_strength_high.isSortingEnabled()
        self.table_fan_strength_high.setSortingEnabled(False)
        item = self.table_fan_strength_high.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_fan_strength_high.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_fan_strength_high.setSortingEnabled(__sortingEnabled)
        self.group_fan_strength_quiet.setTitle(_translate("Dialog_master_slave_test", "Quiet"))
        item = self.table_fan_strength_quiet.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_fan_strength_quiet.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_fan_strength_quiet.isSortingEnabled()
        self.table_fan_strength_quiet.setSortingEnabled(False)
        item = self.table_fan_strength_quiet.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_fan_strength_quiet.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_fan_strength_quiet.setSortingEnabled(__sortingEnabled)
        self.group_fan_new_strength.setTitle(_translate("Dialog_master_slave_test", "風量α"))
        self.group_fan_new_strength_hihi.setTitle(_translate("Dialog_master_slave_test", "Hi-Hi"))
        item = self.table_fan_new_strength_hihi.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_fan_new_strength_hihi.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_fan_new_strength_hihi.isSortingEnabled()
        self.table_fan_new_strength_hihi.setSortingEnabled(False)
        item = self.table_fan_new_strength_hihi.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_fan_new_strength_hihi.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_fan_new_strength_hihi.setSortingEnabled(__sortingEnabled)
        self.group_fan_new_strength_mehi.setTitle(_translate("Dialog_master_slave_test", "Me-Hi"))
        item = self.table_fan_new_strength_mehi.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_fan_new_strength_mehi.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_fan_new_strength_mehi.isSortingEnabled()
        self.table_fan_new_strength_mehi.setSortingEnabled(False)
        item = self.table_fan_new_strength_mehi.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_fan_new_strength_mehi.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_fan_new_strength_mehi.setSortingEnabled(__sortingEnabled)
        self.group_fan_new_strength_lolo.setTitle(_translate("Dialog_master_slave_test", "Lo-Lo"))
        item = self.table_fan_new_strength_lolo.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_fan_new_strength_lolo.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_fan_new_strength_lolo.isSortingEnabled()
        self.table_fan_new_strength_lolo.setSortingEnabled(False)
        item = self.table_fan_new_strength_lolo.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_fan_new_strength_lolo.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_fan_new_strength_lolo.setSortingEnabled(__sortingEnabled)
        self.group_horizontal.setTitle(_translate("Dialog_master_slave_test", "左右風向板"))
        self.group_horizontal_1.setTitle(_translate("Dialog_master_slave_test", "# 1"))
        item = self.table_horizontal_1.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_horizontal_1.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_horizontal_1.isSortingEnabled()
        self.table_horizontal_1.setSortingEnabled(False)
        item = self.table_horizontal_1.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_horizontal_1.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_horizontal_1.setSortingEnabled(__sortingEnabled)
        self.group_horizontal_2.setTitle(_translate("Dialog_master_slave_test", "# 2"))
        item = self.table_horizontal_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_horizontal_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_horizontal_2.isSortingEnabled()
        self.table_horizontal_2.setSortingEnabled(False)
        item = self.table_horizontal_2.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_horizontal_2.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_horizontal_2.setSortingEnabled(__sortingEnabled)
        self.group_horizontal_3.setTitle(_translate("Dialog_master_slave_test", "# 3"))
        item = self.table_horizontal_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_horizontal_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_horizontal_3.isSortingEnabled()
        self.table_horizontal_3.setSortingEnabled(False)
        item = self.table_horizontal_3.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_horizontal_3.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_horizontal_3.setSortingEnabled(__sortingEnabled)
        self.group_horizontal_4.setTitle(_translate("Dialog_master_slave_test", "# 4"))
        item = self.table_horizontal_4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_horizontal_4.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_horizontal_4.isSortingEnabled()
        self.table_horizontal_4.setSortingEnabled(False)
        item = self.table_horizontal_4.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_horizontal_4.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_horizontal_4.setSortingEnabled(__sortingEnabled)
        self.group_vertical.setTitle(_translate("Dialog_master_slave_test", "上下風向板"))
        self.group_vertical_1.setTitle(_translate("Dialog_master_slave_test", "# 1"))
        item = self.table_vertical_1.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_vertical_1.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_vertical_1.isSortingEnabled()
        self.table_vertical_1.setSortingEnabled(False)
        item = self.table_vertical_1.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_vertical_1.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_vertical_1.setSortingEnabled(__sortingEnabled)
        self.group_vertical_2.setTitle(_translate("Dialog_master_slave_test", "# 2"))
        item = self.table_vertical_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_vertical_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_vertical_2.isSortingEnabled()
        self.table_vertical_2.setSortingEnabled(False)
        item = self.table_vertical_2.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_vertical_2.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_vertical_2.setSortingEnabled(__sortingEnabled)
        self.group_vertical_3.setTitle(_translate("Dialog_master_slave_test", "# 3"))
        item = self.table_vertical_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_vertical_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_vertical_3.isSortingEnabled()
        self.table_vertical_3.setSortingEnabled(False)
        item = self.table_vertical_3.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_vertical_3.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_vertical_3.setSortingEnabled(__sortingEnabled)
        self.group_vertical_4.setTitle(_translate("Dialog_master_slave_test", "# 4"))
        item = self.table_vertical_4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_vertical_4.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_vertical_4.isSortingEnabled()
        self.table_vertical_4.setSortingEnabled(False)
        item = self.table_vertical_4.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_vertical_4.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_vertical_4.setSortingEnabled(__sortingEnabled)
        self.group_other.setTitle(_translate("Dialog_master_slave_test", "その他"))
        self.group_eco.setTitle(_translate("Dialog_master_slave_test", "Economy"))
        item = self.table_eco.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_eco.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_eco.isSortingEnabled()
        self.table_eco.setSortingEnabled(False)
        item = self.table_eco.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_eco.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_eco.setSortingEnabled(__sortingEnabled)
        self.group_anti.setTitle(_translate("Dialog_master_slave_test", "Anti-freeze"))
        item = self.table_anti.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_anti.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_anti.isSortingEnabled()
        self.table_anti.setSortingEnabled(False)
        item = self.table_anti.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_anti.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_anti.setSortingEnabled(__sortingEnabled)
        self.group_test.setTitle(_translate("Dialog_master_slave_test", "Test"))
        item = self.table_test.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_test.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_test.isSortingEnabled()
        self.table_test.setSortingEnabled(False)
        item = self.table_test.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_test.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_test.setSortingEnabled(__sortingEnabled)
        self.group_filter.setTitle(_translate("Dialog_master_slave_test", "Filter sign"))
        item = self.table_filter.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_filter.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_filter.isSortingEnabled()
        self.table_filter.setSortingEnabled(False)
        item = self.table_filter.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_filter.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_filter.setSortingEnabled(__sortingEnabled)
        self.group_sensor.setTitle(_translate("Dialog_master_slave_test", "人感センサ"))
        self.group_auto_save.setTitle(_translate("Dialog_master_slave_test", "Auto Save"))
        item = self.table_auto_save.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_auto_save.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_auto_save.isSortingEnabled()
        self.table_auto_save.setSortingEnabled(False)
        item = self.table_auto_save.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_auto_save.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_auto_save.setSortingEnabled(__sortingEnabled)
        self.group_auto_on_off.setTitle(_translate("Dialog_master_slave_test", "On/Off"))
        item = self.table_auto_on_off.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_auto_on_off.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_auto_on_off.isSortingEnabled()
        self.table_auto_on_off.setSortingEnabled(False)
        item = self.table_auto_on_off.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_auto_on_off.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_auto_on_off.setSortingEnabled(__sortingEnabled)
        self.group_auto_off.setTitle(_translate("Dialog_master_slave_test", "Auto Off"))
        item = self.table_auto_off.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_master_slave_test", "親機"))
        item = self.table_auto_off.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_master_slave_test", "子機"))
        __sortingEnabled = self.table_auto_off.isSortingEnabled()
        self.table_auto_off.setSortingEnabled(False)
        item = self.table_auto_off.item(0, 0)
        item.setText(_translate("Dialog_master_slave_test", "親"))
        item = self.table_auto_off.item(0, 1)
        item.setText(_translate("Dialog_master_slave_test", "子"))
        self.table_auto_off.setSortingEnabled(__sortingEnabled)
        self.btn_cancel_master_slave.setText(_translate("Dialog_master_slave_test", "キャンセル"))
        self.btn_create_master_slave.setText(_translate("Dialog_master_slave_test", "作成"))
        self.btn_select_all_master_slave.setText(_translate("Dialog_master_slave_test", "反転"))

